### ISSUE TITLE
What was kingnet53 trained on?

### ISSUE THREAD

**Issue by bc-bytes** [kytimmylai/DFUC2022#1]
As per title. Was the kingnet53 backbone trained on polyps or DFU?

**Comment by kytimmylai** [comment]
@bc-bytes Yes, it's pre-trained on ImageNet-1K

**Comment by bc-bytes** [comment]
Thanks for the info.

**Comment by bc-bytes** [comment]
Would you be able to provide the code for how you created the pretrained weights? I would like to create new pretrained weights using other datasets.

**Comment by kytimmylai** [comment]
Hi, you can refer to the [HarDNet](https://github.com/PingoLH/Pytorch-HarDNet) which is our origin work. I will suggest you also refer to other recent works to get a better performance.
