### ISSUE TITLE
How to create pretrained weights?

### ISSUE THREAD

**Issue by bc-bytes** [kytimmylai/DFUC2022#2]
I have used your model to train a model from scratch for use as pretrained weights (model A). In kingnet.py I have set:

`model = KingNet(arch=53, pretrained=False)`

Once model A is trained, I want to train a second model (model B), and I want to use model A as the pretrained weights. In kingnet.py I set as follows:

`model = KingNet(arch=53, pretrained=True)`

And I also set the path for model A:

```
if(pretrained):
  ##Modify: pretrained path
  weight_file = 'weights/model_a.pth'
  if not os.path.isfile(weight_file):
    print(weight_file, 'is not found')
    exit(0)
  weights = torch.load(weight_file)
  state_dict=weights["state_dict"]
  new_state_dict = OrderedDict()
  for k, v in state_dict.items():
    name = k[7:] # remove `module.`
    new_state_dict[name] = v
  # load params
  self.load_state_dict(new_state_dict)
```

However, I get the following error:

```
Traceback (most recent call last):
  File "/home/seg/HarDNet/train.py", line 197, in <module>
    model = build_model() #opt.modelname, opt.class_num, opt.arch)
  File "/home/seg/HarDNet/utils/utils.py", line 69, in build_model
    model = KingMSEG_lawin_loss4(class_num=class_num).cuda()
  File "/home/seg/HarDNet/lib/HarDMSEG.py", line 39, in __init__
    self.backbone = kingnet53(arch=53, depth_wise=False, pretrained=True)
  File "/home/seg/HarDNet/lib/kingnet.py", line 269, in kingnet53
    model = KingNet(arch=53, pretrained=True)
  File "/home/seg/HarDNet/lib/kingnet.py", line 243, in __init__
    state_dict=weights["state_dict"]
KeyError: 'state_dict'
```

Do you know what the problem might be? The model definitions for model A and model B are identical, I did not change them. When I use kingnet53.pth as pretrained weights, the model trains without error. Do you know what the issue might be?

**Comment by kytimmylai** [comment]
You can study the PyTorch structure first. The error message is clear. You should try to debug with it because it's an basic skill that you should have.

Some suggestions, you can check how it be saved and accessed then you should get the answer.
```
# what's the difference?

torch.save(model.state_dict(), path)
torch.save({'state_dict': model.state_dict(), ...}, path)

weight = torch.load(path)
weight = torch.load(path)['state_dict'])

model.load(weight)
```

**Comment by bc-bytes** [comment]
Thanks for your recommendations. I tried changing save model in train.py as follows:

torch.save({'state_dict': model.state_dict()}, path)

Once model A had trained, I then tried training model B, loading model A as pretrained weights (kingnet.py):

weight_file = 'weights/model_a.pth'
weights = torch.load(weight_file)['state_dict']
self.load_state_dict(weights)

However, that gave Missing key(s) and Unexpected key(s) errors:

https://pastebin.com/MKT4cpAG

**Comment by bc-bytes** [comment]
I also tried this:

```
if(pretrained):
  ##Modify: pretrained path
  weight_file = 'weights/model_a.pth'
  if not os.path.isfile(weight_file):
    print(weight_file, 'is not found')
    exit(0)
  weights = torch.load(weight_file)['state_dict']
  state_dict = weights['state_dict']
  new_state_dict = OrderedDict()
  for k, v in state_dict.items():
    name = k[7:] # remove `module.`
    new_state_dict[name] = v
  # load params
  self.load_state_dict(new_state_dict)
```

But the state_dict is still not found:

```
Traceback (most recent call last):
  File "/home/seg/HarDNet/train.py", line 197, in <module>
    model = build_model() #opt.modelname, opt.class_num, opt.arch)
  File "/home/seg/HarDNet/utils/utils.py", line 69, in build_model
    model = KingMSEG_lawin_loss4(class_num=class_num).cuda()
  File "/home/seg/HarDNet/lib/HarDMSEG.py", line 39, in __init__
    self.backbone = kingnet53(arch=53, depth_wise=False, pretrained=True)
  File "/home/seg/HarDNet/lib/kingnet.py", line 270, in kingnet53
    model = KingNet(arch=53, pretrained=True)
  File "/home/seg/HarDNet/lib/kingnet.py", line 244, in __init__
    state_dict = weights['state_dict']
KeyError: 'state_dict'
```

**Comment by kytimmylai** [comment]
I think you need time to figure out the relation of the question and the error.

> 
> ```
> # what's the difference?
> 
> torch.save(model.state_dict(), path)
> torch.save({'state_dict': model.state_dict(), ...}, path)
> 
> weight = torch.load(path)
> weight = torch.load(path)['state_dict'])
> 
> model.load(weight)
> ```

Your first approach is right but you should not take the second attempt if you are understood.

The error https://pastebin.com/MKT4cpAG depends on your pretrian. You should trace the origin process and fin the reason by yourself.
